### ISSUE TITLE
我要如何实现

### ISSUE THREAD

**Issue by XABxab123** [hlzz/DeepMatchVO#2]
您好，我想问如何用摄像头获取的视频在你的程序上进行测距

**Comment by hlzz** [comment]
@XAB745220zt Hi, do you mean estimate depths using your own data? You can just resize your images to the input size and feed them to the network (refer to demo.py). You may also need to re-train the network to get better results since these cameras may have different intrinsic parameters.

**Comment by XABxab123** [comment]
Yes, I want to use the camera to collect the video, and then measure the distance of the object. The problem is this. My picture is 640x480. I detected the center coordinate of the object. I want to get the distance through this coordinate, so I can measure the world coordinate X, Y. ,Z

**Comment by XABxab123** [comment]
But I am afraid of resize, after the problem, I want the output to be the same size as the original image.

**Comment by XABxab123** [comment]
@hlzz  HI ， I don't understand how the following is calculated. I want to calculate the world coordinates X, Y, Z of a certain coordinate. How to proceed?

def normalize_depth_for_display(depth, pc=95, crop_percent=0, normalizer=None, cmap='gray'):
    # convert to disparity
    depth = 1./(depth + 1e-6)
    if normalizer is not None:
        depth = depth/normalizer
    else:
        depth = depth/(np.percentile(depth, pc) + 1e-6)
    depth = np.clip(depth, 0, 1)
    depth = gray2rgb(depth, cmap=cmap)
    keep_H = int(depth.shape[0] * (1-crop_percent))
    depth = depth[:keep_H]
    return depth

**Comment by hlzz** [comment]
The depth value you obtain using this method is up to scale, which means you cannot get absolute coordination that is aligned with the real world space.

**Comment by XABxab123** [comment]
@hlzz 呃呃呃呃，我好难过，我是否可以获取视差?

**Comment by XABxab123** [comment]
@hlzz Do you have any good suggestions for me to think this

**Comment by hlzz** [comment]
Thanks for your interest. I may not fully understand you but this work may not fulfill your need. Can you elaborate what you want to do?

**Comment by XABxab123** [comment]
@hlzz Thank you for being so patient to listen to me as a newcomer. I want to do something like this. I can detect the object through yolo, then get the center coordinates of the frame, and get the world coordinates X, Y, Z of the object through stereo vision. I used opencv. I tried the effect is not ideal, it may be that I will not optimize the stereo matching algorithm of opencv

**Comment by XABxab123** [comment]
Therefore, I turned to deep learning and obtained parallax. I don’t know what depth estimation is, and I don’t know the difference between it and stereo matching in deep learning.

**Comment by hlzz** [comment]
I guess you want to detect an object in the image and get its world coordinate? Then you need to first define a coordination system, right? If you want to do it with monocular depth estimation (like this work). The depth value you obtain cannot be aligned with the real world space that we live in. So let’s say you have two cameras with known baseline (the distance between them), it is feasible to get its world coordinate, by stereo matching. This is the difference between monocular depth estimation and stereo vision. The former needs only one image, the latter needs image pairs.

**Comment by XABxab123** [comment]
@hlzz Yes, I have a binocular camera with a parallel model, but I don't know where to start, i seems to try all the methods.，Can you tell me how to do it?

**Comment by hlzz** [comment]
You can start with opencv. There are plenty of tutorials for stereo matching using opencv

**Comment by XABxab123** [comment]
@hlzz I tried BM, SGBM, but the effect is not good.
