### ISSUE TITLE
can not reproduce full trajectory of 09 sequence

### ISSUE THREAD

**Issue by AdamAsh2019** [hlzz/DeepMatchVO#3]
hi, firstly thanks for making your work public. recently i try to reproduce 09 sequence full pose trajectory compared with ground-truth by using the python package evo and the pre-trained model 258000.ckpt. However, the result seems that the odometry scale can not be adjusted by the evo automatically as you demonstrated in your article. I wonder how you address the undefined scale issue. (09 dash line is ground truth, 09_full is result of pre-trained model)

 my command is :~/work/DeepMatchVO/output$ evo_traj kitti 09_full.txt --ref=09.txt -p --plot_mode=xz
![微信图片_20190411100533](https://user-images.githubusercontent.com/34387207/55926171-de60e600-5c42-11e9-8113-54ea07460cad.png)

**Comment by hlzz** [comment]
Hi @Adamquhao , try to add '-vas' to this command, which does alignment using a similarity transformation. Hope it helps!

**Comment by AdamAsh2019** [comment]
> Hi @Adamquhao , try to add '-vas' to this command, which does alignment using a similarity transformation. Hope it helps!

oh! it did work! thank you very much!
![ima2ge](https://user-images.githubusercontent.com/34387207/55958974-6b845900-5c9c-11e9-8bf4-71486bbc9de9.png)

**Comment by hlzz** [comment]
@Adamquhao Cool! Glad that you have solved the problem.
