### ISSUE TITLE
About deterministic mask

### ISSUE THREAD

**Issue by WANGYINGYU** [hlzz/DeepMatchVO#4]
Hello,
This is a great work, I'm really interested in it. And I want to know where the deterministic mask is defined in your code, I tried to find it in the location of total_loss( 157 line in this file) in the deep_slam.py but I didn't find it. I want to know how it is defined in the code, because I have some doubts about this part of the paper. Thank you.

**Comment by hlzz** [comment]
@wangyingyu Thanks for your interest! See line 117-126 for what you are looking for.

**Comment by WANGYINGYU** [comment]
@hlzz Hi,
I read the code about the deterministic mask. I'am confused about the following code:
`curr_proj_error = tf.multiply(curr_proj_error, mask)` in line 115 in deep_slam.py
I want to know what the mask is and why we should multiply the mask with curr_proj_error.
Thank you.

**Comment by hlzz** [comment]
@wangyingyu This mask is used for removing out-of-bound pixels/errors, which means pixel visible in, say image 1 but not in image 2. If you run the code and visualize the mask using tensorboard, you will see the mask.
