### ISSUE TITLE
How to generate sequence 00~08 pose ground truth for evaluation

### ISSUE THREAD

**Issue by BassyKuo** [hlzz/DeepMatchVO#5]
Hi, I tried to evaluate the model on sequence 00\~08. I used [dump_pose_seq_TUM](https://github.com/hlzz/DeepMatchVO/blob/master/kitti_eval/pose_evaluation_utils.py#L372L384) function to translate the pose from [data/prepare_train_data.py](https://github.com/hlzz/DeepMatchVO/blob/master/data/prepare_train_data.py#L69L71) as the ground truth. There are ATE errors of sequence 00\~10 by using eval_pose.py. (ground truth 09\~10 in [pose_data/](https://github.com/hlzz/DeepMatchVO/tree/master/kitti_eval/pose_data/ground_truth/seq3), 00\~08 generated by myself)
![image](https://user-images.githubusercontent.com/6426781/59566826-e2bcdb80-9097-11e9-9c76-94ce1282fa37.png)
I doubt that ground truths 00\~08 are generated incorrectly, which causes the error to be so large. Could you tell me how to get the ground truth pose for evaluation? Thanks.

**Comment by hlzz** [comment]
@BassyKuo I don't know which part you did wrong. Are the pose files for 00-08 generated by this repo?
