### ISSUE TITLE
Trajectory Points 

### ISSUE THREAD

**Issue by danbo2** [hlzz/DeepMatchVO#6]
Hi Tianwei,

Can I get all trajectory points coordinate in your method ? Unlike ORB_SLAM2 only export KeyFrame trajectory points coordiante.

Thanks,
Yiyi

**Comment by hlzz** [comment]
@danbo2 You mean all the camera poses? I think so, the learning-based method can work with all frames.

**Comment by danbo2** [comment]
@hlzz Thanks, I guess all camera poses are not under global coordinate. If so, how can I convert all camera poses to global coordinate.

**Comment by hlzz** [comment]
@danbo2 You can either align the (scale of) pose snippets incrementally or use some motion averaging methods.
